### ISSUE TITLE
Pytorch implementation of MV-MWM

### ISSUE THREAD

**Issue by davidoort** [KarlXing/RL-Visual-Continuous-Control#3]
Hi Karl,
are there plans to add a pytorch implementation of https://github.com/younggyoseo/MV-MWM ?

Would be really great!

**Comment by KarlXing** [comment]
Hi David, unfortunately, I don't have the plan to implement MV-MWM for now because of limited bandwidth. However, if you have concrete/interesting research ideas based on that, I will consider collaborating and implementing it.
